#!/bin/sh

SOUND=$(amixer | head -6 | tail -1)
VOL=$(echo "$SOUND" | cut -d" " -f7 | tr -d "[]")
SIMBOL="?"

if echo "$SOUND" | grep -q "\[on\]";
then
    SIMBOL="🔈"
else
    SIMBOL="🔇"
fi

echo "$SIMBOL $VOL"
