#!/bin/sh

if cmus-remote -Q | grep -q "not running";
then   
	exit 0
fi

SONG=$(cmus-remote -Q | grep title | cut -c 11-)
ARTIST=$(cmus-remote -Q | grep "set artist" | head -1 | cut -c 12-)
ST=$(cmus-remote -Q | head -1 | cut -f2 -d" " | sed 's/.*/\u&/')
DURS=$(cmus-remote -Q | grep duration | cut -c 10-)
POSS=$(cmus-remote -Q | grep position | cut -c 10-)

DUR=$(date -d @$DURS +%M:%S)
POS=$(date -d @$POSS +%M:%S)
PROG="$POS - $DUR"

if [ ! -z "$SONG" ] && [ ! -z "$ARTIST" ]
then
	echo "$ST $SONG - $ARTIST $PROG"
fi

if [ ! -z "$SONG" ] && [ -z "$ARTIST" ]
then
	echo "$ST $SONG $PROG"
fi

if [ -z "$SONG" ] && [ ! -z "$ARTIST" ]
then
	echo "$ST $ARTIST $PROG"
fi
